### ISSUE TITLE
Criminology #rstats teaching at Uni of Manchester

### ISSUE THREAD

**Issue by maczokni** [rstudio-education/rstats-ed#26]
Hiya! We have some courses that fit in the list of in person uni courses!

UG 2nd year: "Modelling Criminological Data": bookdown: https://jjmedinaariza.github.io/modelling_book/ (code: https://github.com/jjmedinaariza/modelling_book)

UG 3rd year/ PGT: "Crime Mapping in R": bookdown: https://maczokni.github.io/crimemapping_textbook_bookdown/ (code: https://github.com/maczokni/crimemapping_textbook_bookdown)

PGT: "R for Criminologists": http://jjmedinaariza.github.io/R-for-Criminologists/

Let me know if you need more info for it to be included?

**Comment by mine-cetinkaya-rundel** [comment]
Thank you, I will add these on! (Or feel free to do a PR directly)

PGT is post graduate?
