### ISSUE TITLE
Remove the Link to DataCamp's R resources?

### ISSUE THREAD

**Issue by gavinsimpson** [rstudio-education/rstats-ed#27]
The `README.md` mentions and links to DataCamp resources for learning R. Following all the leadership failures and  abhorrent behaviour exhibit by this company's leadership team in light of an admitted incident of sexual assault/misconduct by the CEO, might removing the links to said company's courses be in the best interests of course developers and potential students?

**Comment by mine-cetinkaya-rundel** [comment]
@gavinsimpson Absolutely, my bad for missing this link earlier.

**Comment by gavinsimpson** [comment]
Awesome; thanks Mine!
