### ISSUE TITLE
psych252 stanford

### ISSUE THREAD

**Issue by tobiasgerstenberg** [rstudio-education/rstats-ed#29]
This course offers an introduction to advanced topics in statistics with the focus of understanding data in the behavioral and social sciences. It is a practical course in which learning statistical concepts and building models in R go hand in hand. The course is organized into three parts: In the first part, we will learn how to visualize, wrangle, and simulate data in R. In the second part, we will cover topics in frequentist statistics (such as multiple regression, logistic regression, and mixed effects models) using the general linear model as an organizing framework. We will learn how to compare models using simulation methods such as bootstrapping and cross-validation. In the third part, we will focus on Bayesian data analysis as an alternative framework for answering statistical questions.

instructor website: [Tobias Gerstenberg](http://cicl.stanford.edu/member/tobias_gerstenberg)
course website: [https://psych252.github.io/](https://psych252.github.io/)
course notes: [https://psych252.github.io/psych252book/](https://psych252.github.io/psych252book/)
course slides: [https://github.com/psych252/psych252slides](https://github.com/psych252/psych252slides)

**Comment by mine-cetinkaya-rundel** [comment]
Thank you, now added!
