### ISSUE TITLE
R Course - online materials

### ISSUE THREAD

**Issue by JimDuggan** [rstudio-education/rstats-ed#3]
Hi,

Here is a link to online materials for an R course taught at the National University of Ireland Galway.

It is being updated weekly, and all content will be completed by the end of November.

https://github.com/JimDuggan/CT5102

regards
Jim.

**Comment by mine-cetinkaya-rundel** [comment]
Thanks @JimDuggan, added!

**Comment by JimDuggan** [comment]
Many thanks!

Regards
Jim.
--
Dr. Jim Duggan,
Senior Lecturer in Information Technology,
College of Engineering & Informatics,
National University of Ireland Galway.

Phone:   +353-91-493336
Email:      jim.duggan@nuigalway.ie<applewebdata://BA43F8E8-0D7F-4D7A-BDE8-B012648F90AC/jim.duggan@nuigalway.ie>
LinkedIn: http://ie.linkedin.com/in/jduggan
Web:         http://bit.ly/1QXGqyM
Github:     https://github.com/JimDuggan
Twitter:   @_jimduggan
Recent Grant Award: https://gcgh.grandchallenges.org/grant/healthsim-supply-chain-simulator-supply-chains
Simulation Book: http://www.springer.com/us/book/9783319340418
Managing Editor, System Dynamics Review
http://onlinelibrary.wiley.com/journal/10.1002/%28ISSN%291099-1727
Ryan Institute Principal Investigator: http://www.nuigalway.ie/ryaninstitute/
